Repository UnBArqDsw2022-2/2022.2-CopoCheio, pull requests merged in 2022-11, with the labels that each got.

#3 Docs: add rich picture on 1.1 development stage
  docs/Base/1.1 docs/RichPicture/rich_picture_filipe.png
Labels: documentation

#5 Docs: Add Filipe contribution info
  docs/Base/1.1.AbordagemNaoEspecifica.md
  docs/Base/1.4.ParticipacoesBase.md
Labels: documentation

#8 docs(Base): refactor documentation
  docs/Base/1.1.2.PlanoDeRiscos.md
  docs/Base/1.1.3.DiagramaCausaEfeito.md
  docs/Base/1.1.4.EstimativaCusto.md
  docs/Base/1.1.5.5W2H.md
  docs/Base/1.1.6.Lexico.md
  docs/Base/1.1.AbordagemNaoEspecifica.md
  docs/Base/1.4.ParticipacoesBase.md
  docs/Base/assets/PlanoDeRiscos/CopoCheioRiscos.svg
  docs/Base/assets/PlanoDeRiscos/DrinkRecipe.drawio.svg
  docs/README.md
  docs/_sidebar.md
Labels: documentation, enhancement

#12 Correções rápidas
  docs/Base/1.2.1.Metodologias.md
  docs/Base/1.2.2.BPMN.md
  docs/Base/1.2.ProcessosMetodologiasAbordagens.md
  docs/Base/assets/bpmn/bpmn.jpg
  docs/Base/assets/bpmn/bpmn.png
  docs/README.md
  docs/_sidebar.md
Labels: documentation

#17 Docs/fix cause effect diagram
  docs/Base/1.1.3.DiagramaCausaEfeito.md
  docs/Base/assets/DiagramaCausaEfeito/diagrama_causa_efeito.jpg
  docs/Base/assets/DiagramaCausaEfeito/diagrama_causa_efeito.png
Labels: documentation, wontfix
